# Generated by Django 2.0.1 on 2018-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoverEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('detail', models.TextField(verbose_name='detail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/rover')),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
    ]
