# Generated by Django 2.0.1 on 2020-05-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoverEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('detail', models.TextField(verbose_name='detail')),
                ('image', models.ImageField(blank=True, upload_to='images/rover')),
                ('eng_title', models.CharField(default='eng', max_length=50, verbose_name='eng_title')),
                ('eng_detail', models.TextField(default='eng', verbose_name='eng_detail')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoverPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_review', models.FileField(blank=True, upload_to='documents/rover', verbose_name='design review file')),
            ],
            options={
                'verbose_name': 'Rover Page',
                'verbose_name_plural': 'Rover Page',
            },
        ),
        migrations.CreateModel(
            name='RoverSubEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('detail', models.TextField(verbose_name='detail')),
                ('image', models.ImageField(blank=True, upload_to='images/rover')),
                ('eng_title', models.CharField(default='eng', max_length=50, verbose_name='eng_title')),
                ('eng_detail', models.TextField(default='eng', verbose_name='eng_detail')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subentries', to='rover.RoverEntry', verbose_name='parent of subentry')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
