# Generated by Django 2.0.1 on 2018-05-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoverSubEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('detail', models.TextField(verbose_name='detail')),
                ('image', models.ImageField(blank=True, upload_to='images/rover')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='roverentry',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/rover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roversubentry',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subentries', to='rover.RoverEntry', verbose_name='parent of subentry'),
        ),
    ]
