# Generated by Django 2.0.1 on 2018-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0002_auto_20180501_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoverPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_review', models.FileField(blank=True, upload_to='documents/rover')),
            ],
            options={
                'verbose_name_plural': 'Rover Page',
                'verbose_name': 'Rover Page',
            },
        ),
    ]
