# Generated by Django 2.0.1 on 2018-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0003_roverpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverpage',
            name='design_review',
            field=models.FileField(blank=True, upload_to='documents/rover', verbose_name='design review file'),
        ),
    ]
