# Generated by Django 2.0.1 on 2019-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0004_auto_20180501_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='roverentry',
            name='eng_detail',
            field=models.TextField(default='', verbose_name='eng_detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roverentry',
            name='eng_title',
            field=models.CharField(default='', max_length=50, verbose_name='eng_title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roversubentry',
            name='eng_detail',
            field=models.TextField(default='', verbose_name='eng_detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roversubentry',
            name='eng_title',
            field=models.CharField(default='', max_length=50, verbose_name='eng_title'),
            preserve_default=False,
        ),
    ]
