# Generated by Django 2.0.1 on 2020-02-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0004_auto_20180501_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='roverentry',
            name='eng_detail',
            field=models.TextField(default='eng', verbose_name='eng_detail'),
        ),
        migrations.AddField(
            model_name='roverentry',
            name='eng_title',
            field=models.CharField(default='eng', max_length=50, verbose_name='eng_title'),
        ),
        migrations.AddField(
            model_name='roversubentry',
            name='eng_detail',
            field=models.TextField(default='eng', verbose_name='eng_detail'),
        ),
        migrations.AddField(
            model_name='roversubentry',
            name='eng_title',
            field=models.CharField(default='eng', max_length=50, verbose_name='eng_title'),
        ),
    ]
