# Generated by Django 2.0.1 on 2019-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='eng_answer',
            field=models.TextField(default='', verbose_name='eng_answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqentry',
            name='eng_question',
            field=models.TextField(default='', verbose_name='eng_question'),
            preserve_default=False,
        ),
    ]
