# Generated by Django 2.0.1 on 2018-01-31 16:10

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=core.utils.slider_image_upload_to)),
                ('show_title', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('priority', 'title'),
            },
        ),
    ]
