# Generated by Django 2.0.1 on 2018-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='priority',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
