# Generated by Django 2.0.1 on 2018-02-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180227_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
