# Generated by Django 2.0.1 on 2020-05-16 11:56

import core.defaults
from django.db import migrations, models
import django.db.models.deletion
import members.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('photo', models.ImageField(upload_to=members.utils.get_upload_path, verbose_name='photo')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='phone number')),
                ('year', models.PositiveSmallIntegerField(default=core.defaults.current_year, verbose_name='active year')),
                ('is_retired', models.BooleanField(default=False, verbose_name='is member retired?')),
                ('did_work', models.BooleanField(default=False, verbose_name="if True: This person will be shown on 'graduated' pagewith the infos of 'working' and 'eng_working'")),
                ('description', models.CharField(blank=True, max_length=75, verbose_name='description (e.g. department)')),
                ('eng_description', models.CharField(blank=True, max_length=75, verbose_name='english description (e.g. department)')),
                ('linkedin_link', models.TextField(blank=True, null=True, verbose_name='Linkedin profile link of this person')),
                ('working', models.TextField(blank=True, null=True, verbose_name='working experiences')),
                ('eng_working', models.TextField(blank=True, null=True, verbose_name='english working experiences')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembersPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(blank=True, upload_to='documents/team')),
                ('team_photo', models.ImageField(blank=True, upload_to='images/members')),
                ('year', models.PositiveSmallIntegerField(default=core.defaults.current_year, unique=True, verbose_name='team year')),
            ],
            options={
                'verbose_name': 'Members Page',
                'verbose_name_plural': 'Members Page',
            },
        ),
        migrations.CreateModel(
            name='SubTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='subteam name')),
                ('eng_name', models.CharField(db_index=True, default='eng_name', max_length=50, verbose_name='subteam eng name')),
                ('leaders', models.ManyToManyField(blank=True, related_name='leader_of', to='members.Member', verbose_name='subteam leaders')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeamAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('photo', models.ImageField(upload_to=members.utils.get_upload_path, verbose_name='photo')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='phone number')),
                ('year', models.PositiveSmallIntegerField(default=core.defaults.current_year, verbose_name='active year')),
                ('is_retired', models.BooleanField(default=False, verbose_name='is member retired?')),
                ('did_work', models.BooleanField(default=False, verbose_name="if True: This person will be shown on 'graduated' pagewith the infos of 'working' and 'eng_working'")),
                ('description', models.CharField(max_length=75, verbose_name='description (e.g. department)')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='members.Member', verbose_name='team leader')),
            ],
            options={
                'verbose_name': 'team leader',
                'verbose_name_plural': 'team leader',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.SubTeam', verbose_name='subteam of member'),
        ),
    ]
