# Generated by Django 2.0.1 on 2018-01-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamleader',
            options={'verbose_name': 'team leader', 'verbose_name_plural': 'team leader'},
        ),
    ]
