# Generated by Django 2.0.1 on 2020-06-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subteam',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='subteam',
            name='name',
            field=models.CharField(db_index=True, default='name', max_length=50, verbose_name='subteam name'),
        ),
    ]
