# Generated by Django 2.0.1 on 2018-01-31 09:10

from django.db import migrations, models
import members.utils


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180122_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AlterModelOptions(
            name='subteam',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='teamadvisor',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=members.utils.get_upload_path, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='teamadvisor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=members.utils.get_upload_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(db_index=True, max_length=25, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='subteam name'),
        ),
        migrations.AlterField(
            model_name='teamadvisor',
            name='first_name',
            field=models.CharField(db_index=True, max_length=25, verbose_name='first name'),
        ),
    ]
