# Generated by Django 2.0.1 on 2020-09-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200613_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamadvisor',
            name='eng_description',
            field=models.CharField(default='Team Advisor', max_length=75, verbose_name='eng description (e.g. department)'),
        ),
    ]
