# Generated by Django 2.0.1 on 2018-01-31 12:35

from django.db import migrations, models
import members.utils


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180131_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=members.utils.get_upload_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='teamadvisor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=members.utils.get_upload_path, verbose_name='photo'),
        ),
    ]
