# Generated by Django 2.0.1 on 2018-02-28 11:21

from django.db import migrations, models
import members.utils


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180131_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='hey', upload_to=members.utils.get_upload_path, verbose_name='photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamadvisor',
            name='photo',
            field=models.ImageField(default='hey', upload_to=members.utils.get_upload_path, verbose_name='photo'),
            preserve_default=False,
        ),
    ]
