# Generated by Django 2.0.1 on 2018-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180228_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(upload_to='documents/team')),
            ],
            options={
                'verbose_name': 'members page',
                'verbose_name_plural': 'members page',
            },
        ),
    ]
