# Generated by Django 2.0.1 on 2018-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_memberspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberspage',
            name='team_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/members'),
        ),
        migrations.AlterField(
            model_name='memberspage',
            name='proposal',
            field=models.FileField(blank=True, upload_to='documents/team'),
        ),
    ]
