# Generated by Django 2.0.1 on 2018-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20180501_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberspage',
            name='team_photo',
            field=models.ImageField(blank=True, default='', upload_to='images/members'),
            preserve_default=False,
        ),
    ]
