# Generated by Django 2.0.1 on 2018-05-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180501_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberspage',
            options={'verbose_name': 'Members Page', 'verbose_name_plural': 'Members Page'},
        ),
    ]
