# Generated by Django 2.0.1 on 2019-03-23 15:53

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20180501_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.PositiveSmallIntegerField(default=core.defaults.current_year, verbose_name=''),
        ),
        migrations.AddField(
            model_name='teamadvisor',
            name='year',
            field=models.PositiveSmallIntegerField(default=core.defaults.current_year, verbose_name=''),
        ),
    ]
