# Generated by Django 2.0.1 on 2019-03-23 15:53

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20190323_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.PositiveSmallIntegerField(default=core.utils.current_year, verbose_name='active year'),
        ),
        migrations.AlterField(
            model_name='teamadvisor',
            name='year',
            field=models.PositiveSmallIntegerField(default=core.utils.current_year, verbose_name='active year'),
        ),
    ]
