# Generated by Django 2.0.1 on 2019-03-23 19:33

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20190323_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberspage',
            name='year',
            field=models.PositiveSmallIntegerField(default=core.utils.current_year, verbose_name='team year'),
        ),
    ]
