# Generated by Django 2.0.1 on 2019-03-23 19:38

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_memberspage_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberspage',
            name='year',
            field=models.PositiveSmallIntegerField(default=core.utils.current_year, unique=True, verbose_name='team year'),
        ),
    ]
