# Generated by Django 2.0.1 on 2019-03-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20190323_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subteam',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of', to='members.Member', verbose_name='subteam leader'),
        ),
    ]
