# Generated by Django 2.0.1 on 2019-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20190325_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subteam',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='leader_of', to='members.Member', verbose_name='subteam leaders'),
        ),
    ]
