# Generated by Django 2.0.1 on 2020-01-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20191115_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='eng_description',
            field=models.CharField(blank=True, max_length=75, verbose_name='description (e.g. department)'),
        ),
    ]
