# Generated by Django 2.0.1 on 2020-01-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_member_eng_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subteam',
            name='eng_name',
            field=models.CharField(db_index=True, default='eng_name', max_length=50, verbose_name='subteam name'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='name',
            field=models.CharField(db_index=True, default='name', max_length=50, verbose_name='subteam name'),
        ),
    ]
