# Generated by Django 2.0.1 on 2020-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20200131_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='eng_working',
            field=models.TextField(blank=True, null=True, verbose_name='working experiences'),
        ),
        migrations.AddField(
            model_name='member',
            name='working',
            field=models.TextField(blank=True, null=True, verbose_name='working experiences'),
        ),
    ]
