# Generated by Django 2.0.1 on 2020-02-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20200201_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamadvisor',
            name='did_work',
            field=models.BooleanField(default=False),
        ),
    ]
