# Generated by Django 2.0.1 on 2020-02-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_teamadvisor_did_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='eng_team_role',
            field=models.TextField(blank=True, null=True, verbose_name='eng - what was the roles of this person in team?this is for graduated page'),
        ),
        migrations.AddField(
            model_name='member',
            name='team_role',
            field=models.TextField(blank=True, null=True, verbose_name='what was the roles of this person in team?this is for graduated page'),
        ),
        migrations.AlterField(
            model_name='member',
            name='did_work',
            field=models.BooleanField(default=False, verbose_name="if True: This person will be shown on 'graduated' pagewith the infos of 'working' and 'eng_working'"),
        ),
        migrations.AlterField(
            model_name='teamadvisor',
            name='did_work',
            field=models.BooleanField(default=False, verbose_name="if True: This person will be shown on 'graduated' pagewith the infos of 'working' and 'eng_working'"),
        ),
    ]
