# Generated by Django 2.0.1 on 2020-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20200201_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='linkedin_link',
            field=models.TextField(blank=True, null=True, verbose_name='Linkedin profile link of this person'),
        ),
    ]
