# Generated by Django 2.0.1 on 2020-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='left',
            field=models.CharField(default=11, max_length=2, verbose_name='space from left, in %'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='top',
            field=models.CharField(default=10, max_length=2, verbose_name='space from top, in %'),
        ),
    ]
