# Generated by Django 2.0.1 on 2020-09-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='eng_grade',
            field=models.TextField(blank=True, default='Grade', null=True),
        ),
    ]
