# Generated by Django 2.0.1 on 2018-02-28 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainpageentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpageentry',
            name='is_old',
            field=models.BooleanField(default=False, help_text='is this entry still newsworthy??'),
        ),
        migrations.AddField(
            model_name='mainpageentry',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
