# Generated by Django 2.0.1 on 2020-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200516_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='rover_image_width',
            field=models.CharField(default=10, max_length=2, verbose_name='width of rover image, in %'),
        ),
    ]
