# Generated by Django 2.0.1 on 2020-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sliderimage_rover_image_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='left',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='rover_image_width',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='top',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='place',
            field=models.CharField(default=0, max_length=2, verbose_name='Place of rover. if it is first, make this zero'),
        ),
    ]
