# Generated by Django 2.0.1 on 2019-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180228_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('year', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
    ]
