# Generated by Django 2.0.1 on 2020-05-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200520_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='place',
        ),
    ]
