# Generated by Django 2.0.1 on 2019-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainrovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageentry',
            name='eng_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpageentry',
            name='eng_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
