# Generated by Django 2.0.1 on 2020-05-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_sliderimage_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='place',
            field=models.SmallIntegerField(default=0, max_length=2),
        ),
    ]
