# Generated by Django 2.0.1 on 2019-11-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainrovers_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrovers',
            name='exp_eng',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
