# Generated by Django 2.0.1 on 2019-11-30 14:23

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mainrovers_exp_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrovers',
            name='image',
            field=models.ImageField(upload_to=main.utils.slider_image_upload_to),
        ),
    ]
