# Generated by Django 2.0.1 on 2020-01-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldyears', '0002_auto_20200110_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldyear',
            name='year',
            field=models.CharField(max_length=4, unique=True, verbose_name='team year'),
        ),
    ]
