# Generated by Django 2.0.1 on 2018-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutentry',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='aboutentry',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
