# Generated by Django 2.0.1 on 2019-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180227_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutentry',
            name='eng_detail',
            field=models.TextField(default='', verbose_name='eng_detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutentry',
            name='eng_title',
            field=models.CharField(default='', max_length=50, verbose_name='eng_title'),
            preserve_default=False,
        ),
    ]
