# Generated by Django 2.0.1 on 2020-02-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180227_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutentry',
            name='eng_detail',
            field=models.TextField(default='eng', verbose_name='eng_detail'),
        ),
        migrations.AddField(
            model_name='aboutentry',
            name='eng_title',
            field=models.CharField(default='eng', max_length=50, verbose_name='eng_title'),
        ),
        migrations.AddField(
            model_name='aboutentry',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/about'),
        ),
    ]
