# Generated by Django 2.0.1 on 2020-01-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20191123_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutentry',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/about'),
        ),
    ]
