# Generated by Django 2.0.1 on 2020-07-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200614_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm_model',
        ),
        migrations.DeleteModel(
            name='SupportForm',
        ),
    ]
