# Generated by Django 2.0.1 on 2020-07-27 19:26

import core.defaults
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/sponsors')),
                ('display_width', models.PositiveSmallIntegerField(help_text='in pixels')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('website', models.URLField(verbose_name='website')),
                ('sponsorship_year', models.PositiveSmallIntegerField(default=core.defaults.current_year)),
                ('is_name_on_display', models.BooleanField(default=False, verbose_name='put name under the image on display?')),
                ('is_old', models.BooleanField(default=False, verbose_name='is sponsor old?')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SponsorshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=30, verbose_name='type name')),
                ('eng_name', models.CharField(default='eng', max_length=30, verbose_name='English type name')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'support page',
                'verbose_name_plural': 'support page',
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='sponsors.SponsorshipType', verbose_name='type of sponsorship'),
        ),
    ]
