# Generated by Django 2.0.1 on 2018-01-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('display_width', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_name_on_display', models.BooleanField(default=False, verbose_name='put name under the image on display?')),
                ('is_old', models.BooleanField(default=False, verbose_name='is sponsor old?')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='type name')),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='sponsors.SponsorshipType', verbose_name='type of sponsorship'),
        ),
    ]
