# Generated by Django 2.0.1 on 2018-01-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.URLField(default='hey', verbose_name='website'),
            preserve_default=False,
        ),
    ]
