# Generated by Django 2.0.1 on 2020-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20200727_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshiptype',
            name='eng_name',
            field=models.CharField(default='eng', max_length=30, verbose_name='English type name'),
        ),
    ]
