# Generated by Django 2.0.1 on 2018-01-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiptype',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
