# Generated by Django 2.0.1 on 2018-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_auto_20180131_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiptype',
            name='description',
            field=models.TextField(default='Açıklama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsorshiptype',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
