# Generated by Django 2.0.1 on 2018-02-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_auto_20180227_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorshiptype',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='sponsorshiptype',
            old_name='priority',
            new_name='order',
        ),
    ]
