# Generated by Django 2.0.1 on 2018-02-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_auto_20180227_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='display_width',
            field=models.PositiveSmallIntegerField(help_text='in pixels'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(upload_to='images/sponsors'),
        ),
    ]
