# Generated by Django 2.0.1 on 2018-03-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0009_supportpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportpage',
            options={'verbose_name': 'support page', 'verbose_name_plural': 'support page'},
        ),
    ]
