# Generated by Django 2.0.1 on 2018-05-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0010_auto_20180307_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('name',)},
        ),
    ]
