# Generated by Django 2.0.1 on 2019-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_auto_20180501_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship_year',
            field=models.PositiveSmallIntegerField(default=2019),
        ),
    ]
