# Generated by Django 2.0.1 on 2019-03-02 09:41

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0012_sponsor_sponsorship_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsorship_year',
            field=models.PositiveSmallIntegerField(default=core.defaults.current_year),
        ),
    ]
