# Generated by Django 2.0.1 on 2019-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_auto_20190302_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='eng_name',
            field=models.CharField(default='', max_length=50, verbose_name='eng name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshiptype',
            name='eng_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshiptype',
            name='eng_name',
            field=models.CharField(default='', max_length=30, verbose_name='eng type name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportpage',
            name='eng_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
