# Generated by Django 2.0.1 on 2019-12-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0014_auto_20191123_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsor_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/sponsors')),
                ('display_width', models.PositiveSmallIntegerField(help_text='in pixels')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('eng_name', models.CharField(max_length=50, verbose_name='eng name')),
                ('sponsorship_year', models.PositiveSmallIntegerField(verbose_name='default=current_year')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='sponsor_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=30, verbose_name='type name')),
                ('eng_name', models.CharField(max_length=30, verbose_name='eng type name')),
                ('description', models.TextField()),
                ('eng_description', models.TextField()),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsorship_type',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='SponsorshipType',
        ),
    ]
