# Generated by Django 2.0.1 on 2020-01-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0015_auto_20191221_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor_new',
            name='website',
            field=models.URLField(default='www.servisbiziz.com', verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='sponsor_new',
            name='sponsorship_year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
