# Generated by Django 2.0.1 on 2020-01-31 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0018_auto_20200120_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor_new',
            name='sponsorship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='sponsors.sponsor_type', verbose_name='type of sponsorship'),
        ),
    ]
